config/routes.rb
Rails.application.routes.draw do
  get 'plants/new'
  get 'plants/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :gardens, only: [:show] do
    resources :plants, only: [:new, :create]
  end
  resources :plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants

  validates :name, :picture, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

 validates :species, :picture, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def show
    @garden = Garden.find(params[:id])
    @plants = @garden.plants
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def new
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:species, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.picture %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

  <div class="container mt-3">
  <!--   <div class="d-flex"> -->
  <div class="cards">

     <% @plants.each do |plant| %>
        <div class="mr-3">
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.picture %>")>
            <div><%= plant.species %></div>
          </div>
        <div class="text-right trash">
           <%= link_to plant_path(plant),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </div>
        </div>
      <% end %>

  </div>
   <!--  </div> -->
    <%= link_to "Add a plant", new_garden_plant_path(@garden), class: "btn btn-primary mt-3" %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsParkAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/new.html.erb
<div class="container">
  <h1>Add a plant</h1>
  <%= simple_form_for [@garden, @plant] do |f| %>
    <%= f.input :species %>
    <%= f.input :picture %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>